module SceneProtos.$0.LayerSettings exposing
    ( LayerDataType(..)
    , LayerT
    )

{-| This module is generated by Messenger, don't modify this.

@docs LayerDataType
@docs LayerT

-}

import Lib.Layer.Base exposing (Layer)
import SceneProtos.$0.LayerBase exposing (CommonData)
$1


{-| LayerDataType
-}
type LayerDataType
    = $2
    | NullLayerData


{-| LayerT
-}
type alias LayerT =
    Layer LayerDataType CommonData
