module Scenes.$0.Export exposing
    ( Data
    , scene
    )

{-| Export Module

This module is generated by Messenger, don't modify this.

@docs Data
@docs scene

-}

import Lib.Scene.Base exposing (Scene)
import Scenes.$0.Common exposing (Model)
import Scenes.$0.Model exposing (initModel, updateModel, viewModel)


{-| Data
-}
type alias Data =
    Model


{-| scene
-}
scene : Scene Data
scene =
    { init = initModel
    , update = updateModel
    , view = viewModel
    }
