module Scenes.$0.Global exposing
    ( dataToSDT
    , sdtToData
    , sceneToST
    )

{-| This is the doc for this module

Automatically generated by Messenger.

Don't modify this file.

@docs dataToSDT
@docs sdtToData
@docs sdtToData

-}

import Canvas exposing (Renderable)
import Lib.Env.Env exposing (Env)
import Lib.Scene.Base exposing (Scene, SceneInitData, SceneOutputMsg)
import Scenes.$0.Export exposing (Data, nullData)
import Scenes.SceneSettings exposing (SceneDataTypes(..), SceneT)


{-| dataToSDT
-}
dataToSDT : Data -> SceneDataTypes
dataToSDT d =
    $0DataT d


{-| sdtToData
-}
sdtToData : SceneDataTypes -> Data
sdtToData dt =
    case dt of
        $0DataT x ->
            x

        _ ->
            nullData


{-| sceneToST
-}
sceneToST : Scene Data -> SceneT
sceneToST sd =
    let
        init : Env -> SceneInitData -> SceneDataTypes
        init t tm =
            dataToSDT (sd.init t tm)

        update : Env -> SceneDataTypes -> ( SceneDataTypes, List SceneOutputMsg, Env )
        update env sdt =
            let
                ( newm, som, newgd ) =
                    sd.update env (sdtToData sdt)
            in
            ( dataToSDT newm, som, newgd )

        view : Env -> SceneDataTypes -> Renderable
        view env sdt =
            sd.view env (sdtToData sdt)
    in
    { init = init
    , update = update
    , view = view
    }
